model:
    base_learning_rate: 4.5e-5
    target: ldm.models.autoencoder.AutoencoderKL
    params:
        monitor: "val/rec_loss"
        # ckpt_path: "logs/2023-05-16T13-19-09_mnist_autoencoder/checkpoints/epoch=000027.ckpt"
        ckpt_path: trained_models/autoenocder_model_16-05.ckpt
        embed_dim: 4
        lossconfig:
            target: ldm.modules.losses.LPIPSWithDiscriminator
            params:
                disc_start: 10001
                kl_weight: 0.1
                disc_weight: 0.5
                disc_in_channels: 1
        ddconfig:
            double_z: True
            z_channels: 4
            resolution: 128
            in_channels: 1
            out_ch: 1
            ch: 32
            ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
            num_res_blocks: 2
            attn_resolutions: [ ]
            dropout: 0.1
            tanh_out: True

data:
    target: main.DataModuleFromConfig
    params:
        batch_size: 8
        wrap: True
        train:
            target: custom.data.mnist_dataset.MNISTTrain
            params:
                size: 128
        validation:
            target: custom.data.mnist_dataset.MNISTValidation
            params:
                size: 128
        test:
            target: custom.data.mnist_dataset.MNISTTest
            params:
                size: 128      
        

lightning:
    callbacks:
        image_logger:
            target: main.ImageLogger
            params:
                batch_frequency: 1000
                max_images: 8
                increase_log_steps: True

    trainer:
        benchmark: True
        accumulate_grad_batches: 2
