model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 10001
        kl_weight: 0.1
        disc_weight: 0.5
        disc_in_channels: 1
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 128
      in_channels: 1
      out_ch: 1
      ch: 32
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.1
      tanh_out: true
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    wrap: true
    train:
      target: custom.data.mnist_dataset.MNISTTrain
      params:
        size: 128
    validation:
      target: custom.data.mnist_dataset.MNISTValidation
      params:
        size: 128
